import Head from 'next/head'

import { styled } from '@linaria/react'

export default function Home() {
  return (
    <_Container>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <_Main>
        <_Title>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </_Title>
      </_Main>
    </_Container>
  )
}

const _Container = styled.div`
  padding: 0 2rem;
`

const _Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`

const _Title = styled.h1`
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
`
